# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 5
    cpus_per_task: 1
    gpus_per_node: null
    tasks_per_node: 1
    mem_gb: 1
    nodes: 1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: default
    qos: null
    comment: null
    constraint: null
    exclude: null
    gres: null
    cpus_per_gpu: null
    gpus_per_task: null
    mem_per_gpu: null
    mem_per_cpu: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters:
      account: rrg-bengioy-ad
    array_parallelism: 256
    setup:
      - |
        DOMAIN=$(hostname -d)
        case $DOMAIN in
          narval.calcul.quebec)
            GATEWAY="narval2"
            ;;
          graham.sharcnet)
            GATEWAY="gra-login1"
            ;;
          *)
            echo "Failed to find gateway on $DOMAIN"
            exit 1
            ;;
        esac
        for ((i=0; i<100; ++i)); do
          LOCALPORT=$(shuf -i 1024-65535 -n 1)
          echo "Attempting to connect on $LOCALPORT"
          ssh -D $LOCALPORT $GATEWAY -N -f -vvv && break
        done || { echo "Giving up forwarding port after $i attempts..."; exit 1; }
        export ALL_PROXY=socks5://127.0.0.1:$LOCALPORT

run_host: compute_canada

wandb:
  mode: online

